#!/bin/sh

logger -p auth.info -t lock-screen screen locked
# for xscreensaver:
exec xscreensaver-command -lock
# for gnome-screensaver:
#exec gnome-screensaver-command --activate
# for KDE:
#qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
